version: "3"

services:
  mysql:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build: .
    restart: unless-stopped
    image: cargo-loading
    ports:
      - "8080:8080"
  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./scripts/deploy-pm2/nginx-default:/etc/nginx/sites-available/default